//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtsAPCC.CardValidation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CardValidation.ICardValidationService")]
    public interface ICardValidationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardValidationService/ValidateCard", ReplyAction="http://tempuri.org/ICardValidationService/ValidateCardResponse")]
        bool ValidateCard(string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardValidationService/ValidateCard", ReplyAction="http://tempuri.org/ICardValidationService/ValidateCardResponse")]
        System.Threading.Tasks.Task<bool> ValidateCardAsync(string cardNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICardValidationServiceChannel : AtsAPCC.CardValidation.ICardValidationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardValidationServiceClient : System.ServiceModel.ClientBase<AtsAPCC.CardValidation.ICardValidationService>, AtsAPCC.CardValidation.ICardValidationService {
        
        public CardValidationServiceClient() {
        }
        
        public CardValidationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardValidationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardValidationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardValidationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateCard(string cardNumber) {
            return base.Channel.ValidateCard(cardNumber);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateCardAsync(string cardNumber) {
            return base.Channel.ValidateCardAsync(cardNumber);
        }
    }
}
