//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 
namespace AtsATPCC.AutoPayCreditCardService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IAutoPayCreditCardService", Namespace="http://tempuri.org/")]
    public partial class AutoPayCreditCardService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IsEligibleForAutoPayCCOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnrollAutoPayCCOperationCompleted;
        
        /// <remarks/>
        public AutoPayCreditCardService() {
            this.Url = "http://maxedout/NwnStWsRouter/IVRRoutingServices.svc/AutoPayEndPoint";
        }
        
        /// <remarks/>
        public event IsEligibleForAutoPayCCCompletedEventHandler IsEligibleForAutoPayCCCompleted;
        
        /// <remarks/>
        public event EnrollAutoPayCCCompletedEventHandler EnrollAutoPayCCCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAutoPayCreditCardService/IsEligibleForAutoPayCC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AutoPayEligibilityResponse IsEligibleForAutoPayCC([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string accountNumber) {
            object[] results = this.Invoke("IsEligibleForAutoPayCC", new object[] {
                        accountNumber});
            return ((AutoPayEligibilityResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsEligibleForAutoPayCC(string accountNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsEligibleForAutoPayCC", new object[] {
                        accountNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public AutoPayEligibilityResponse EndIsEligibleForAutoPayCC(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AutoPayEligibilityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void IsEligibleForAutoPayCCAsync(string accountNumber) {
            this.IsEligibleForAutoPayCCAsync(accountNumber, null);
        }
        
        /// <remarks/>
        public void IsEligibleForAutoPayCCAsync(string accountNumber, object userState) {
            if ((this.IsEligibleForAutoPayCCOperationCompleted == null)) {
                this.IsEligibleForAutoPayCCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsEligibleForAutoPayCCOperationCompleted);
            }
            this.InvokeAsync("IsEligibleForAutoPayCC", new object[] {
                        accountNumber}, this.IsEligibleForAutoPayCCOperationCompleted, userState);
        }
        
        private void OnIsEligibleForAutoPayCCOperationCompleted(object arg) {
            if ((this.IsEligibleForAutoPayCCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsEligibleForAutoPayCCCompleted(this, new IsEligibleForAutoPayCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAutoPayCreditCardService/EnrollAutoPayCC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AutoPayEnrollCreditCardResponse EnrollAutoPayCC([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string accountNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string firstName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lastName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emailAddress, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string creditCardLast4, System.DateTime enrollDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool enrollDateSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string signature, CreditCardTypes creditCardType, [System.Xml.Serialization.XmlIgnoreAttribute()] bool creditCardTypeSpecified, System.DateTime creditCardExpDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool creditCardExpDateSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string referenceId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nameOnCard) {
            object[] results = this.Invoke("EnrollAutoPayCC", new object[] {
                        accountNumber,
                        firstName,
                        lastName,
                        phoneNumber,
                        emailAddress,
                        creditCardLast4,
                        enrollDate,
                        enrollDateSpecified,
                        signature,
                        creditCardType,
                        creditCardTypeSpecified,
                        creditCardExpDate,
                        creditCardExpDateSpecified,
                        referenceId,
                        nameOnCard});
            return ((AutoPayEnrollCreditCardResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEnrollAutoPayCC(
                    string accountNumber, 
                    string firstName, 
                    string lastName, 
                    string phoneNumber, 
                    string emailAddress, 
                    string creditCardLast4, 
                    System.DateTime enrollDate, 
                    bool enrollDateSpecified, 
                    string signature, 
                    CreditCardTypes creditCardType, 
                    bool creditCardTypeSpecified, 
                    System.DateTime creditCardExpDate, 
                    bool creditCardExpDateSpecified, 
                    string referenceId, 
                    string nameOnCard, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return this.BeginInvoke("EnrollAutoPayCC", new object[] {
                        accountNumber,
                        firstName,
                        lastName,
                        phoneNumber,
                        emailAddress,
                        creditCardLast4,
                        enrollDate,
                        enrollDateSpecified,
                        signature,
                        creditCardType,
                        creditCardTypeSpecified,
                        creditCardExpDate,
                        creditCardExpDateSpecified,
                        referenceId,
                        nameOnCard}, callback, asyncState);
        }
        
        /// <remarks/>
        public AutoPayEnrollCreditCardResponse EndEnrollAutoPayCC(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AutoPayEnrollCreditCardResponse)(results[0]));
        }
        
        /// <remarks/>
        public void EnrollAutoPayCCAsync(string accountNumber, string firstName, string lastName, string phoneNumber, string emailAddress, string creditCardLast4, System.DateTime enrollDate, bool enrollDateSpecified, string signature, CreditCardTypes creditCardType, bool creditCardTypeSpecified, System.DateTime creditCardExpDate, bool creditCardExpDateSpecified, string referenceId, string nameOnCard) {
            this.EnrollAutoPayCCAsync(accountNumber, firstName, lastName, phoneNumber, emailAddress, creditCardLast4, enrollDate, enrollDateSpecified, signature, creditCardType, creditCardTypeSpecified, creditCardExpDate, creditCardExpDateSpecified, referenceId, nameOnCard, null);
        }
        
        /// <remarks/>
        public void EnrollAutoPayCCAsync(
                    string accountNumber, 
                    string firstName, 
                    string lastName, 
                    string phoneNumber, 
                    string emailAddress, 
                    string creditCardLast4, 
                    System.DateTime enrollDate, 
                    bool enrollDateSpecified, 
                    string signature, 
                    CreditCardTypes creditCardType, 
                    bool creditCardTypeSpecified, 
                    System.DateTime creditCardExpDate, 
                    bool creditCardExpDateSpecified, 
                    string referenceId, 
                    string nameOnCard, 
                    object userState) {
            if ((this.EnrollAutoPayCCOperationCompleted == null)) {
                this.EnrollAutoPayCCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnrollAutoPayCCOperationCompleted);
            }
            this.InvokeAsync("EnrollAutoPayCC", new object[] {
                        accountNumber,
                        firstName,
                        lastName,
                        phoneNumber,
                        emailAddress,
                        creditCardLast4,
                        enrollDate,
                        enrollDateSpecified,
                        signature,
                        creditCardType,
                        creditCardTypeSpecified,
                        creditCardExpDate,
                        creditCardExpDateSpecified,
                        referenceId,
                        nameOnCard}, this.EnrollAutoPayCCOperationCompleted, userState);
        }
        
        private void OnEnrollAutoPayCCOperationCompleted(object arg) {
            if ((this.EnrollAutoPayCCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnrollAutoPayCCCompleted(this, new EnrollAutoPayCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NWNatural.External.Models.Responses")]
    public partial class AutoPayEligibilityResponse {
        
        private string accountNumberField;
        
        private bool isEligibleField;
        
        private bool isEligibleFieldSpecified;
        
        private AutoPayServiceResponse responseField;
        
        private bool responseFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEligible {
            get {
                return this.isEligibleField;
            }
            set {
                this.isEligibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsEligibleSpecified {
            get {
                return this.isEligibleFieldSpecified;
            }
            set {
                this.isEligibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public AutoPayServiceResponse Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseSpecified {
            get {
                return this.responseFieldSpecified;
            }
            set {
                this.responseFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NWNatural.External.Models.Responses")]
    public enum AutoPayServiceResponse {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NWNatural.External.Models.Responses")]
    public partial class AutoPayEnrollCreditCardResponse {
        
        private string accountNumberField;
        
        private long confirmationField;
        
        private bool confirmationFieldSpecified;
        
        private AutoPayServiceResponse responseField;
        
        private bool responseFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public long Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfirmationSpecified {
            get {
                return this.confirmationFieldSpecified;
            }
            set {
                this.confirmationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public AutoPayServiceResponse Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseSpecified {
            get {
                return this.responseFieldSpecified;
            }
            set {
                this.responseFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NWNatural.External.Models")]
    public enum CreditCardTypes {
        
        /// <remarks/>
        Visa,
        
        /// <remarks/>
        MasterCard,
        
        /// <remarks/>
        Discover,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void IsEligibleForAutoPayCCCompletedEventHandler(object sender, IsEligibleForAutoPayCCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsEligibleForAutoPayCCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsEligibleForAutoPayCCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AutoPayEligibilityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AutoPayEligibilityResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void EnrollAutoPayCCCompletedEventHandler(object sender, EnrollAutoPayCCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnrollAutoPayCCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnrollAutoPayCCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AutoPayEnrollCreditCardResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AutoPayEnrollCreditCardResponse)(this.results[0]));
            }
        }
    }
}
