//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtsAPCC.EnrollCard {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnrollmentResult", Namespace="http://schemas.datacontract.org/2004/07/CardEnrollmentService")]
    [System.SerializableAttribute()]
    public partial class EnrollmentResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FailureReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtsAPCC.EnrollCard.EnrollmentResult.ATIServiceBrokerStatusEnum ResultStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureReason {
            get {
                return this.FailureReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.FailureReasonField, value) != true)) {
                    this.FailureReasonField = value;
                    this.RaisePropertyChanged("FailureReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtsAPCC.EnrollCard.EnrollmentResult.ATIServiceBrokerStatusEnum ResultStatus {
            get {
                return this.ResultStatusField;
            }
            set {
                if ((this.ResultStatusField.Equals(value) != true)) {
                    this.ResultStatusField = value;
                    this.RaisePropertyChanged("ResultStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionIdField, value) != true)) {
                    this.transactionIdField = value;
                    this.RaisePropertyChanged("transactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="EnrollmentResult.ATIServiceBrokerStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/CardEnrollmentService")]
        public enum ATIServiceBrokerStatusEnum : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Success = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            UpdateTokenFailed = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            InvalidToken = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BadEnrollStatus = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BadTransactionData = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TempusBadStatus = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BadTempusCall = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BadAccountOrCard = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Other = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DeactivateCards = 9,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnrollCard.IEnrollCardService")]
    public interface IEnrollCardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnrollCardService/EnrollCard", ReplyAction="http://tempuri.org/IEnrollCardService/EnrollCardResponse")]
        AtsAPCC.EnrollCard.EnrollmentResult EnrollCard(
                    string CustomerName, 
                    string AccountAccountNumber, 
                    string CardFullNumber, 
                    string CardLast4, 
                    int CardExpiresMonth, 
                    int CardExpriresYear, 
                    string CardSecurityCode, 
                    string CardHolderFirstName, 
                    string CardHolderLastName, 
                    string CardHolderInitial, 
                    string CardHolderAppearsOnCard, 
                    string AddressAddress1, 
                    string AddressAddress2, 
                    string AddressAddress3, 
                    string AddressCity, 
                    string AddressState, 
                    string AddressZip, 
                    string ContactTelephone, 
                    string ContactEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnrollCardService/EnrollCard", ReplyAction="http://tempuri.org/IEnrollCardService/EnrollCardResponse")]
        System.Threading.Tasks.Task<AtsAPCC.EnrollCard.EnrollmentResult> EnrollCardAsync(
                    string CustomerName, 
                    string AccountAccountNumber, 
                    string CardFullNumber, 
                    string CardLast4, 
                    int CardExpiresMonth, 
                    int CardExpriresYear, 
                    string CardSecurityCode, 
                    string CardHolderFirstName, 
                    string CardHolderLastName, 
                    string CardHolderInitial, 
                    string CardHolderAppearsOnCard, 
                    string AddressAddress1, 
                    string AddressAddress2, 
                    string AddressAddress3, 
                    string AddressCity, 
                    string AddressState, 
                    string AddressZip, 
                    string ContactTelephone, 
                    string ContactEmail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnrollCardServiceChannel : AtsAPCC.EnrollCard.IEnrollCardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnrollCardServiceClient : System.ServiceModel.ClientBase<AtsAPCC.EnrollCard.IEnrollCardService>, AtsAPCC.EnrollCard.IEnrollCardService {
        
        public EnrollCardServiceClient() {
        }
        
        public EnrollCardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnrollCardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrollCardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrollCardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AtsAPCC.EnrollCard.EnrollmentResult EnrollCard(
                    string CustomerName, 
                    string AccountAccountNumber, 
                    string CardFullNumber, 
                    string CardLast4, 
                    int CardExpiresMonth, 
                    int CardExpriresYear, 
                    string CardSecurityCode, 
                    string CardHolderFirstName, 
                    string CardHolderLastName, 
                    string CardHolderInitial, 
                    string CardHolderAppearsOnCard, 
                    string AddressAddress1, 
                    string AddressAddress2, 
                    string AddressAddress3, 
                    string AddressCity, 
                    string AddressState, 
                    string AddressZip, 
                    string ContactTelephone, 
                    string ContactEmail) {
            return base.Channel.EnrollCard(CustomerName, AccountAccountNumber, CardFullNumber, CardLast4, CardExpiresMonth, CardExpriresYear, CardSecurityCode, CardHolderFirstName, CardHolderLastName, CardHolderInitial, CardHolderAppearsOnCard, AddressAddress1, AddressAddress2, AddressAddress3, AddressCity, AddressState, AddressZip, ContactTelephone, ContactEmail);
        }
        
        public System.Threading.Tasks.Task<AtsAPCC.EnrollCard.EnrollmentResult> EnrollCardAsync(
                    string CustomerName, 
                    string AccountAccountNumber, 
                    string CardFullNumber, 
                    string CardLast4, 
                    int CardExpiresMonth, 
                    int CardExpriresYear, 
                    string CardSecurityCode, 
                    string CardHolderFirstName, 
                    string CardHolderLastName, 
                    string CardHolderInitial, 
                    string CardHolderAppearsOnCard, 
                    string AddressAddress1, 
                    string AddressAddress2, 
                    string AddressAddress3, 
                    string AddressCity, 
                    string AddressState, 
                    string AddressZip, 
                    string ContactTelephone, 
                    string ContactEmail) {
            return base.Channel.EnrollCardAsync(CustomerName, AccountAccountNumber, CardFullNumber, CardLast4, CardExpiresMonth, CardExpriresYear, CardSecurityCode, CardHolderFirstName, CardHolderLastName, CardHolderInitial, CardHolderAppearsOnCard, AddressAddress1, AddressAddress2, AddressAddress3, AddressCity, AddressState, AddressZip, ContactTelephone, ContactEmail);
        }
    }
}
