//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtsAPCC.App_In_Maintenance {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.activetelesource.com/webservices/", ConfigurationName="App_In_Maintenance.UtilitySoap")]
    public interface UtilitySoap {
        
        // CODEGEN: Generating message contract since element name App_Name from namespace http://www.activetelesource.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.activetelesource.com/webservices/App_In_Maintenance", ReplyAction="*")]
        AtsAPCC.App_In_Maintenance.App_In_MaintenanceResponse App_In_Maintenance(AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.activetelesource.com/webservices/App_In_Maintenance", ReplyAction="*")]
        System.Threading.Tasks.Task<AtsAPCC.App_In_Maintenance.App_In_MaintenanceResponse> App_In_MaintenanceAsync(AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class App_In_MaintenanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="App_In_Maintenance", Namespace="http://www.activetelesource.com/webservices/", Order=0)]
        public AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequestBody Body;
        
        public App_In_MaintenanceRequest() {
        }
        
        public App_In_MaintenanceRequest(AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.activetelesource.com/webservices/")]
    public partial class App_In_MaintenanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string App_Name;
        
        public App_In_MaintenanceRequestBody() {
        }
        
        public App_In_MaintenanceRequestBody(string App_Name) {
            this.App_Name = App_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class App_In_MaintenanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="App_In_MaintenanceResponse", Namespace="http://www.activetelesource.com/webservices/", Order=0)]
        public AtsAPCC.App_In_Maintenance.App_In_MaintenanceResponseBody Body;
        
        public App_In_MaintenanceResponse() {
        }
        
        public App_In_MaintenanceResponse(AtsAPCC.App_In_Maintenance.App_In_MaintenanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.activetelesource.com/webservices/")]
    public partial class App_In_MaintenanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool App_In_MaintenanceResult;
        
        public App_In_MaintenanceResponseBody() {
        }
        
        public App_In_MaintenanceResponseBody(bool App_In_MaintenanceResult) {
            this.App_In_MaintenanceResult = App_In_MaintenanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UtilitySoapChannel : AtsAPCC.App_In_Maintenance.UtilitySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilitySoapClient : System.ServiceModel.ClientBase<AtsAPCC.App_In_Maintenance.UtilitySoap>, AtsAPCC.App_In_Maintenance.UtilitySoap {
        
        public UtilitySoapClient() {
        }
        
        public UtilitySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilitySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilitySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilitySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AtsAPCC.App_In_Maintenance.App_In_MaintenanceResponse AtsAPCC.App_In_Maintenance.UtilitySoap.App_In_Maintenance(AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequest request) {
            return base.Channel.App_In_Maintenance(request);
        }
        
        public bool App_In_Maintenance(string App_Name) {
            AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequest inValue = new AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequest();
            inValue.Body = new AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequestBody();
            inValue.Body.App_Name = App_Name;
            AtsAPCC.App_In_Maintenance.App_In_MaintenanceResponse retVal = ((AtsAPCC.App_In_Maintenance.UtilitySoap)(this)).App_In_Maintenance(inValue);
            return retVal.Body.App_In_MaintenanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AtsAPCC.App_In_Maintenance.App_In_MaintenanceResponse> AtsAPCC.App_In_Maintenance.UtilitySoap.App_In_MaintenanceAsync(AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequest request) {
            return base.Channel.App_In_MaintenanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<AtsAPCC.App_In_Maintenance.App_In_MaintenanceResponse> App_In_MaintenanceAsync(string App_Name) {
            AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequest inValue = new AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequest();
            inValue.Body = new AtsAPCC.App_In_Maintenance.App_In_MaintenanceRequestBody();
            inValue.Body.App_Name = App_Name;
            return ((AtsAPCC.App_In_Maintenance.UtilitySoap)(this)).App_In_MaintenanceAsync(inValue);
        }
    }
}
