'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace IPSTools
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.activetelesource.com/webservices/", ConfigurationName:="IPSTools.ToolsSoap")>  _
    Public Interface ToolsSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/ValidABARoutingNumber", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ValidABARoutingNumber(ByVal RoutingNumber As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/ValidABARoutingNumber", ReplyAction:="*")>  _
        Function ValidABARoutingNumberAsync(ByVal RoutingNumber As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/ABABankData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ABABankData(ByVal RoutingNumber As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/ABABankData", ReplyAction:="*")>  _
        Function ABABankDataAsync(ByVal RoutingNumber As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/ValidCreditCardNumber", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ValidCreditCardNumber(ByVal CardNumber As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/ValidCreditCardNumber", ReplyAction:="*")>  _
        Function ValidCreditCardNumberAsync(ByVal CardNumber As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/ValidCreditCardExpiration", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ValidCreditCardExpiration(ByVal MMYY As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/ValidCreditCardExpiration", ReplyAction:="*")>  _
        Function ValidCreditCardExpirationAsync(ByVal MMYY As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/CreditCardType", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CreditCardType(ByVal CardNumber As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/CreditCardType", ReplyAction:="*")>  _
        Function CreditCardTypeAsync(ByVal CardNumber As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/LogACHTransaction", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LogACHTransaction( _
                    ByVal ACH_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal RoutingNumber As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/LogACHTransaction", ReplyAction:="*")>  _
        Function LogACHTransactionAsync( _
                    ByVal ACH_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal RoutingNumber As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As System.Threading.Tasks.Task(Of Long)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/LogCreditCardTransaction", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LogCreditCardTransaction( _
                    ByVal Card_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/LogCreditCardTransaction", ReplyAction:="*")>  _
        Function LogCreditCardTransactionAsync( _
                    ByVal Card_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As System.Threading.Tasks.Task(Of Long)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/LogCreditCardTransaction2", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LogCreditCardTransaction2( _
                    ByVal Card_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantRequestID As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/LogCreditCardTransaction2", ReplyAction:="*")>  _
        Function LogCreditCardTransaction2Async( _
                    ByVal Card_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantRequestID As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As System.Threading.Tasks.Task(Of Long)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/UpdateCreditCardTransaction", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateCreditCardTransaction( _
                    ByVal Card_TransTable As String,  _
                    ByVal Card_TransID As Long,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantRequestID As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/UpdateCreditCardTransaction", ReplyAction:="*")>  _
        Function UpdateCreditCardTransactionAsync( _
                    ByVal Card_TransTable As String,  _
                    ByVal Card_TransID As Long,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantRequestID As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As System.Threading.Tasks.Task(Of Long)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/LogWebHistory", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LogWebHistory( _
                    ByVal Web_HistoryTable As String,  _
                    ByVal Web_ProfileID As Long,  _
                    ByVal SessionID As String,  _
                    ByVal SessionIP As String,  _
                    ByVal SessionStart As Date,  _
                    ByVal SessionFinish As Date,  _
                    ByVal Schedule As String,  _
                    ByVal Credentials As String,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal CardTransID As Long,  _
                    ByVal ACHTransID As Long,  _
                    ByVal WebError As Boolean,  _
                    ByVal TextCaption1 As String,  _
                    ByVal TextCaption2 As String,  _
                    ByVal TextCaption3 As String,  _
                    ByVal TextCaption4 As String,  _
                    ByVal TextCaption5 As String,  _
                    ByVal TextCaption6 As String,  _
                    ByVal TextCaption7 As String,  _
                    ByVal TextCaption8 As String,  _
                    ByVal Text1 As String,  _
                    ByVal Text2 As String,  _
                    ByVal Text3 As String,  _
                    ByVal Text4 As String,  _
                    ByVal Text5 As String,  _
                    ByVal Text6 As String,  _
                    ByVal Text7 As String,  _
                    ByVal Text8 As String,  _
                    ByVal DateCaption1 As String,  _
                    ByVal DateCaption2 As String,  _
                    ByVal DateCaption3 As String,  _
                    ByVal DateCaption4 As String,  _
                    ByVal Date1 As Date,  _
                    ByVal Date2 As Date,  _
                    ByVal Date3 As Date,  _
                    ByVal Date4 As Date,  _
                    ByVal IntegerCaption1 As String,  _
                    ByVal IntegerCaption2 As String,  _
                    ByVal IntegerCaption3 As String,  _
                    ByVal IntegerCaption4 As String,  _
                    ByVal Integer1 As Long,  _
                    ByVal Integer2 As Long,  _
                    ByVal Integer3 As Long,  _
                    ByVal Integer4 As Long,  _
                    ByVal NumericCaption1 As String,  _
                    ByVal NumericCaption2 As String,  _
                    ByVal NumericCaption3 As String,  _
                    ByVal NumericCaption4 As String,  _
                    ByVal Numeric1 As Decimal,  _
                    ByVal Numeric2 As Decimal,  _
                    ByVal Numeric3 As Decimal,  _
                    ByVal Numeric4 As Decimal,  _
                    ByVal MoneyCaption1 As String,  _
                    ByVal MoneyCaption2 As String,  _
                    ByVal MoneyCaption3 As String,  _
                    ByVal MoneyCaption4 As String,  _
                    ByVal Money1 As Double,  _
                    ByVal Money2 As Double,  _
                    ByVal Money3 As Double,  _
                    ByVal Money4 As Double,  _
                    ByVal BitCaption1 As String,  _
                    ByVal BitCaption2 As String,  _
                    ByVal BitCaption3 As String,  _
                    ByVal BitCaption4 As String,  _
                    ByVal Bit1 As Boolean,  _
                    ByVal Bit2 As Boolean,  _
                    ByVal Bit3 As Boolean,  _
                    ByVal Bit4 As Boolean) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/LogWebHistory", ReplyAction:="*")>  _
        Function LogWebHistoryAsync( _
                    ByVal Web_HistoryTable As String,  _
                    ByVal Web_ProfileID As Long,  _
                    ByVal SessionID As String,  _
                    ByVal SessionIP As String,  _
                    ByVal SessionStart As Date,  _
                    ByVal SessionFinish As Date,  _
                    ByVal Schedule As String,  _
                    ByVal Credentials As String,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal CardTransID As Long,  _
                    ByVal ACHTransID As Long,  _
                    ByVal WebError As Boolean,  _
                    ByVal TextCaption1 As String,  _
                    ByVal TextCaption2 As String,  _
                    ByVal TextCaption3 As String,  _
                    ByVal TextCaption4 As String,  _
                    ByVal TextCaption5 As String,  _
                    ByVal TextCaption6 As String,  _
                    ByVal TextCaption7 As String,  _
                    ByVal TextCaption8 As String,  _
                    ByVal Text1 As String,  _
                    ByVal Text2 As String,  _
                    ByVal Text3 As String,  _
                    ByVal Text4 As String,  _
                    ByVal Text5 As String,  _
                    ByVal Text6 As String,  _
                    ByVal Text7 As String,  _
                    ByVal Text8 As String,  _
                    ByVal DateCaption1 As String,  _
                    ByVal DateCaption2 As String,  _
                    ByVal DateCaption3 As String,  _
                    ByVal DateCaption4 As String,  _
                    ByVal Date1 As Date,  _
                    ByVal Date2 As Date,  _
                    ByVal Date3 As Date,  _
                    ByVal Date4 As Date,  _
                    ByVal IntegerCaption1 As String,  _
                    ByVal IntegerCaption2 As String,  _
                    ByVal IntegerCaption3 As String,  _
                    ByVal IntegerCaption4 As String,  _
                    ByVal Integer1 As Long,  _
                    ByVal Integer2 As Long,  _
                    ByVal Integer3 As Long,  _
                    ByVal Integer4 As Long,  _
                    ByVal NumericCaption1 As String,  _
                    ByVal NumericCaption2 As String,  _
                    ByVal NumericCaption3 As String,  _
                    ByVal NumericCaption4 As String,  _
                    ByVal Numeric1 As Decimal,  _
                    ByVal Numeric2 As Decimal,  _
                    ByVal Numeric3 As Decimal,  _
                    ByVal Numeric4 As Decimal,  _
                    ByVal MoneyCaption1 As String,  _
                    ByVal MoneyCaption2 As String,  _
                    ByVal MoneyCaption3 As String,  _
                    ByVal MoneyCaption4 As String,  _
                    ByVal Money1 As Double,  _
                    ByVal Money2 As Double,  _
                    ByVal Money3 As Double,  _
                    ByVal Money4 As Double,  _
                    ByVal BitCaption1 As String,  _
                    ByVal BitCaption2 As String,  _
                    ByVal BitCaption3 As String,  _
                    ByVal BitCaption4 As String,  _
                    ByVal Bit1 As Boolean,  _
                    ByVal Bit2 As Boolean,  _
                    ByVal Bit3 As Boolean,  _
                    ByVal Bit4 As Boolean) As System.Threading.Tasks.Task(Of Long)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/UpdateWebHistoryEventLog", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateWebHistoryEventLog(ByVal Web_HistoryTable As String, ByVal Web_HistoryID As Long, ByVal Web_EventLog As String, ByVal SessionFinish As Date, ByVal CustomerAccountID As String, ByVal CardTransID As Long, ByVal ACHTransID As Long, ByVal WebError As Boolean) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/UpdateWebHistoryEventLog", ReplyAction:="*")>  _
        Function UpdateWebHistoryEventLogAsync(ByVal Web_HistoryTable As String, ByVal Web_HistoryID As Long, ByVal Web_EventLog As String, ByVal SessionFinish As Date, ByVal CustomerAccountID As String, ByVal CardTransID As Long, ByVal ACHTransID As Long, ByVal WebError As Boolean) As System.Threading.Tasks.Task(Of Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/UpdateWebHistoryCustom", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateWebHistoryCustom( _
                    ByVal Web_HistoryTable As String,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal SessionFinish As Date,  _
                    ByVal Schedule As String,  _
                    ByVal Credentials As String,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal CardTransID As Long,  _
                    ByVal ACHTransID As Long,  _
                    ByVal WebError As Boolean,  _
                    ByVal TextCaption1 As String,  _
                    ByVal TextCaption2 As String,  _
                    ByVal TextCaption3 As String,  _
                    ByVal TextCaption4 As String,  _
                    ByVal TextCaption5 As String,  _
                    ByVal TextCaption6 As String,  _
                    ByVal TextCaption7 As String,  _
                    ByVal TextCaption8 As String,  _
                    ByVal Text1 As String,  _
                    ByVal Text2 As String,  _
                    ByVal Text3 As String,  _
                    ByVal Text4 As String,  _
                    ByVal Text5 As String,  _
                    ByVal Text6 As String,  _
                    ByVal Text7 As String,  _
                    ByVal Text8 As String,  _
                    ByVal DateCaption1 As String,  _
                    ByVal DateCaption2 As String,  _
                    ByVal DateCaption3 As String,  _
                    ByVal DateCaption4 As String,  _
                    ByVal Date1 As Date,  _
                    ByVal Date2 As Date,  _
                    ByVal Date3 As Date,  _
                    ByVal Date4 As Date,  _
                    ByVal IntegerCaption1 As String,  _
                    ByVal IntegerCaption2 As String,  _
                    ByVal IntegerCaption3 As String,  _
                    ByVal IntegerCaption4 As String,  _
                    ByVal Integer1 As Long,  _
                    ByVal Integer2 As Long,  _
                    ByVal Integer3 As Long,  _
                    ByVal Integer4 As Long,  _
                    ByVal NumericCaption1 As String,  _
                    ByVal NumericCaption2 As String,  _
                    ByVal NumericCaption3 As String,  _
                    ByVal NumericCaption4 As String,  _
                    ByVal Numeric1 As Decimal,  _
                    ByVal Numeric2 As Decimal,  _
                    ByVal Numeric3 As Decimal,  _
                    ByVal Numeric4 As Decimal,  _
                    ByVal MoneyCaption1 As String,  _
                    ByVal MoneyCaption2 As String,  _
                    ByVal MoneyCaption3 As String,  _
                    ByVal MoneyCaption4 As String,  _
                    ByVal Money1 As Double,  _
                    ByVal Money2 As Double,  _
                    ByVal Money3 As Double,  _
                    ByVal Money4 As Double,  _
                    ByVal BitCaption1 As String,  _
                    ByVal BitCaption2 As String,  _
                    ByVal BitCaption3 As String,  _
                    ByVal BitCaption4 As String,  _
                    ByVal Bit1 As Boolean,  _
                    ByVal Bit2 As Boolean,  _
                    ByVal Bit3 As Boolean,  _
                    ByVal Bit4 As Boolean) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/UpdateWebHistoryCustom", ReplyAction:="*")>  _
        Function UpdateWebHistoryCustomAsync( _
                    ByVal Web_HistoryTable As String,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal SessionFinish As Date,  _
                    ByVal Schedule As String,  _
                    ByVal Credentials As String,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal CardTransID As Long,  _
                    ByVal ACHTransID As Long,  _
                    ByVal WebError As Boolean,  _
                    ByVal TextCaption1 As String,  _
                    ByVal TextCaption2 As String,  _
                    ByVal TextCaption3 As String,  _
                    ByVal TextCaption4 As String,  _
                    ByVal TextCaption5 As String,  _
                    ByVal TextCaption6 As String,  _
                    ByVal TextCaption7 As String,  _
                    ByVal TextCaption8 As String,  _
                    ByVal Text1 As String,  _
                    ByVal Text2 As String,  _
                    ByVal Text3 As String,  _
                    ByVal Text4 As String,  _
                    ByVal Text5 As String,  _
                    ByVal Text6 As String,  _
                    ByVal Text7 As String,  _
                    ByVal Text8 As String,  _
                    ByVal DateCaption1 As String,  _
                    ByVal DateCaption2 As String,  _
                    ByVal DateCaption3 As String,  _
                    ByVal DateCaption4 As String,  _
                    ByVal Date1 As Date,  _
                    ByVal Date2 As Date,  _
                    ByVal Date3 As Date,  _
                    ByVal Date4 As Date,  _
                    ByVal IntegerCaption1 As String,  _
                    ByVal IntegerCaption2 As String,  _
                    ByVal IntegerCaption3 As String,  _
                    ByVal IntegerCaption4 As String,  _
                    ByVal Integer1 As Long,  _
                    ByVal Integer2 As Long,  _
                    ByVal Integer3 As Long,  _
                    ByVal Integer4 As Long,  _
                    ByVal NumericCaption1 As String,  _
                    ByVal NumericCaption2 As String,  _
                    ByVal NumericCaption3 As String,  _
                    ByVal NumericCaption4 As String,  _
                    ByVal Numeric1 As Decimal,  _
                    ByVal Numeric2 As Decimal,  _
                    ByVal Numeric3 As Decimal,  _
                    ByVal Numeric4 As Decimal,  _
                    ByVal MoneyCaption1 As String,  _
                    ByVal MoneyCaption2 As String,  _
                    ByVal MoneyCaption3 As String,  _
                    ByVal MoneyCaption4 As String,  _
                    ByVal Money1 As Double,  _
                    ByVal Money2 As Double,  _
                    ByVal Money3 As Double,  _
                    ByVal Money4 As Double,  _
                    ByVal BitCaption1 As String,  _
                    ByVal BitCaption2 As String,  _
                    ByVal BitCaption3 As String,  _
                    ByVal BitCaption4 As String,  _
                    ByVal Bit1 As Boolean,  _
                    ByVal Bit2 As Boolean,  _
                    ByVal Bit3 As Boolean,  _
                    ByVal Bit4 As Boolean) As System.Threading.Tasks.Task(Of Long)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ToolsSoapChannel
        Inherits IPSTools.ToolsSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ToolsSoapClient
        Inherits System.ServiceModel.ClientBase(Of IPSTools.ToolsSoap)
        Implements IPSTools.ToolsSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ValidABARoutingNumber(ByVal RoutingNumber As String) As Boolean Implements IPSTools.ToolsSoap.ValidABARoutingNumber
            Return MyBase.Channel.ValidABARoutingNumber(RoutingNumber)
        End Function
        
        Public Function ValidABARoutingNumberAsync(ByVal RoutingNumber As String) As System.Threading.Tasks.Task(Of Boolean) Implements IPSTools.ToolsSoap.ValidABARoutingNumberAsync
            Return MyBase.Channel.ValidABARoutingNumberAsync(RoutingNumber)
        End Function
        
        Public Function ABABankData(ByVal RoutingNumber As String) As System.Data.DataSet Implements IPSTools.ToolsSoap.ABABankData
            Return MyBase.Channel.ABABankData(RoutingNumber)
        End Function
        
        Public Function ABABankDataAsync(ByVal RoutingNumber As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements IPSTools.ToolsSoap.ABABankDataAsync
            Return MyBase.Channel.ABABankDataAsync(RoutingNumber)
        End Function
        
        Public Function ValidCreditCardNumber(ByVal CardNumber As String) As Boolean Implements IPSTools.ToolsSoap.ValidCreditCardNumber
            Return MyBase.Channel.ValidCreditCardNumber(CardNumber)
        End Function
        
        Public Function ValidCreditCardNumberAsync(ByVal CardNumber As String) As System.Threading.Tasks.Task(Of Boolean) Implements IPSTools.ToolsSoap.ValidCreditCardNumberAsync
            Return MyBase.Channel.ValidCreditCardNumberAsync(CardNumber)
        End Function
        
        Public Function ValidCreditCardExpiration(ByVal MMYY As String) As Boolean Implements IPSTools.ToolsSoap.ValidCreditCardExpiration
            Return MyBase.Channel.ValidCreditCardExpiration(MMYY)
        End Function
        
        Public Function ValidCreditCardExpirationAsync(ByVal MMYY As String) As System.Threading.Tasks.Task(Of Boolean) Implements IPSTools.ToolsSoap.ValidCreditCardExpirationAsync
            Return MyBase.Channel.ValidCreditCardExpirationAsync(MMYY)
        End Function
        
        Public Function CreditCardType(ByVal CardNumber As String) As String Implements IPSTools.ToolsSoap.CreditCardType
            Return MyBase.Channel.CreditCardType(CardNumber)
        End Function
        
        Public Function CreditCardTypeAsync(ByVal CardNumber As String) As System.Threading.Tasks.Task(Of String) Implements IPSTools.ToolsSoap.CreditCardTypeAsync
            Return MyBase.Channel.CreditCardTypeAsync(CardNumber)
        End Function
        
        Public Function LogACHTransaction( _
                    ByVal ACH_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal RoutingNumber As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As Long Implements IPSTools.ToolsSoap.LogACHTransaction
            Return MyBase.Channel.LogACHTransaction(ACH_TransTable, IVR_HistoryID, IVR_ProfileID, Web_HistoryID, TransDateTime, CustomerID, CustomerAccountID, FirstName, LastName, BillAddr1, BillAddr2, BillCity, BillState, BillZip, RoutingNumber, AccountLast4, AccountType, Fee, Amount, TransAmount, TransIsDebit, TransIsCredit, TransIsChargeback, TransIsVoid, WasVoided, VoidReferenceID, Reconciled, DataTokenID, MerchantID, MerchantReference, MerchantDecision, MerchantReasonCode, MerchantAuthCode, MerchantBatchID, ReconBatchID, ReconDateTime, RecurringPayment, RecurringReferenceID, RecurringReferenceText, Failure, TransNote, Misc1, Misc2, Misc3, Misc4)
        End Function
        
        Public Function LogACHTransactionAsync( _
                    ByVal ACH_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal RoutingNumber As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As System.Threading.Tasks.Task(Of Long) Implements IPSTools.ToolsSoap.LogACHTransactionAsync
            Return MyBase.Channel.LogACHTransactionAsync(ACH_TransTable, IVR_HistoryID, IVR_ProfileID, Web_HistoryID, TransDateTime, CustomerID, CustomerAccountID, FirstName, LastName, BillAddr1, BillAddr2, BillCity, BillState, BillZip, RoutingNumber, AccountLast4, AccountType, Fee, Amount, TransAmount, TransIsDebit, TransIsCredit, TransIsChargeback, TransIsVoid, WasVoided, VoidReferenceID, Reconciled, DataTokenID, MerchantID, MerchantReference, MerchantDecision, MerchantReasonCode, MerchantAuthCode, MerchantBatchID, ReconBatchID, ReconDateTime, RecurringPayment, RecurringReferenceID, RecurringReferenceText, Failure, TransNote, Misc1, Misc2, Misc3, Misc4)
        End Function
        
        Public Function LogCreditCardTransaction( _
                    ByVal Card_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As Long Implements IPSTools.ToolsSoap.LogCreditCardTransaction
            Return MyBase.Channel.LogCreditCardTransaction(Card_TransTable, IVR_HistoryID, IVR_ProfileID, Web_HistoryID, TransDateTime, CustomerID, CustomerAccountID, FirstName, LastName, BillAddr1, BillAddr2, BillCity, BillState, BillZip, AccountLast4, AccountType, Fee, Amount, TransAmount, TransIsDebit, TransIsCredit, TransIsChargeback, TransIsVoid, WasVoided, VoidReferenceID, Reconciled, DataTokenID, MerchantID, MerchantReference, MerchantDecision, MerchantReasonCode, MerchantAuthCode, MerchantAVSCode, MerchantBatchID, ReconBatchID, ReconDateTime, RecurringPayment, RecurringReferenceID, RecurringReferenceText, Failure, TransNote, Misc1, Misc2, Misc3, Misc4)
        End Function
        
        Public Function LogCreditCardTransactionAsync( _
                    ByVal Card_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As System.Threading.Tasks.Task(Of Long) Implements IPSTools.ToolsSoap.LogCreditCardTransactionAsync
            Return MyBase.Channel.LogCreditCardTransactionAsync(Card_TransTable, IVR_HistoryID, IVR_ProfileID, Web_HistoryID, TransDateTime, CustomerID, CustomerAccountID, FirstName, LastName, BillAddr1, BillAddr2, BillCity, BillState, BillZip, AccountLast4, AccountType, Fee, Amount, TransAmount, TransIsDebit, TransIsCredit, TransIsChargeback, TransIsVoid, WasVoided, VoidReferenceID, Reconciled, DataTokenID, MerchantID, MerchantReference, MerchantDecision, MerchantReasonCode, MerchantAuthCode, MerchantAVSCode, MerchantBatchID, ReconBatchID, ReconDateTime, RecurringPayment, RecurringReferenceID, RecurringReferenceText, Failure, TransNote, Misc1, Misc2, Misc3, Misc4)
        End Function
        
        Public Function LogCreditCardTransaction2( _
                    ByVal Card_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantRequestID As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As Long Implements IPSTools.ToolsSoap.LogCreditCardTransaction2
            Return MyBase.Channel.LogCreditCardTransaction2(Card_TransTable, IVR_HistoryID, IVR_ProfileID, Web_HistoryID, TransDateTime, CustomerID, CustomerAccountID, FirstName, LastName, BillAddr1, BillAddr2, BillCity, BillState, BillZip, AccountLast4, AccountType, Fee, Amount, TransAmount, TransIsDebit, TransIsCredit, TransIsChargeback, TransIsVoid, WasVoided, VoidReferenceID, Reconciled, DataTokenID, MerchantID, MerchantReference, MerchantRequestID, MerchantDecision, MerchantReasonCode, MerchantAuthCode, MerchantAVSCode, MerchantBatchID, ReconBatchID, ReconDateTime, RecurringPayment, RecurringReferenceID, RecurringReferenceText, Failure, TransNote, Misc1, Misc2, Misc3, Misc4)
        End Function
        
        Public Function LogCreditCardTransaction2Async( _
                    ByVal Card_TransTable As String,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantRequestID As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As System.Threading.Tasks.Task(Of Long) Implements IPSTools.ToolsSoap.LogCreditCardTransaction2Async
            Return MyBase.Channel.LogCreditCardTransaction2Async(Card_TransTable, IVR_HistoryID, IVR_ProfileID, Web_HistoryID, TransDateTime, CustomerID, CustomerAccountID, FirstName, LastName, BillAddr1, BillAddr2, BillCity, BillState, BillZip, AccountLast4, AccountType, Fee, Amount, TransAmount, TransIsDebit, TransIsCredit, TransIsChargeback, TransIsVoid, WasVoided, VoidReferenceID, Reconciled, DataTokenID, MerchantID, MerchantReference, MerchantRequestID, MerchantDecision, MerchantReasonCode, MerchantAuthCode, MerchantAVSCode, MerchantBatchID, ReconBatchID, ReconDateTime, RecurringPayment, RecurringReferenceID, RecurringReferenceText, Failure, TransNote, Misc1, Misc2, Misc3, Misc4)
        End Function
        
        Public Function UpdateCreditCardTransaction( _
                    ByVal Card_TransTable As String,  _
                    ByVal Card_TransID As Long,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantRequestID As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As Long Implements IPSTools.ToolsSoap.UpdateCreditCardTransaction
            Return MyBase.Channel.UpdateCreditCardTransaction(Card_TransTable, Card_TransID, IVR_HistoryID, IVR_ProfileID, Web_HistoryID, TransDateTime, CustomerID, CustomerAccountID, FirstName, LastName, BillAddr1, BillAddr2, BillCity, BillState, BillZip, AccountLast4, AccountType, Fee, Amount, TransAmount, TransIsDebit, TransIsCredit, TransIsChargeback, TransIsVoid, WasVoided, VoidReferenceID, Reconciled, DataTokenID, MerchantID, MerchantReference, MerchantRequestID, MerchantDecision, MerchantReasonCode, MerchantAuthCode, MerchantAVSCode, MerchantBatchID, ReconBatchID, ReconDateTime, RecurringPayment, RecurringReferenceID, RecurringReferenceText, Failure, TransNote, Misc1, Misc2, Misc3, Misc4)
        End Function
        
        Public Function UpdateCreditCardTransactionAsync( _
                    ByVal Card_TransTable As String,  _
                    ByVal Card_TransID As Long,  _
                    ByVal IVR_HistoryID As Long,  _
                    ByVal IVR_ProfileID As Long,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal TransDateTime As Date,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal BillAddr1 As String,  _
                    ByVal BillAddr2 As String,  _
                    ByVal BillCity As String,  _
                    ByVal BillState As String,  _
                    ByVal BillZip As String,  _
                    ByVal AccountLast4 As String,  _
                    ByVal AccountType As String,  _
                    ByVal Fee As Decimal,  _
                    ByVal Amount As Decimal,  _
                    ByVal TransAmount As Decimal,  _
                    ByVal TransIsDebit As Boolean,  _
                    ByVal TransIsCredit As Boolean,  _
                    ByVal TransIsChargeback As Boolean,  _
                    ByVal TransIsVoid As Boolean,  _
                    ByVal WasVoided As Boolean,  _
                    ByVal VoidReferenceID As Long,  _
                    ByVal Reconciled As Boolean,  _
                    ByVal DataTokenID As String,  _
                    ByVal MerchantID As String,  _
                    ByVal MerchantReference As String,  _
                    ByVal MerchantRequestID As String,  _
                    ByVal MerchantDecision As String,  _
                    ByVal MerchantReasonCode As String,  _
                    ByVal MerchantAuthCode As String,  _
                    ByVal MerchantAVSCode As String,  _
                    ByVal MerchantBatchID As Long,  _
                    ByVal ReconBatchID As Long,  _
                    ByVal ReconDateTime As Date,  _
                    ByVal RecurringPayment As Boolean,  _
                    ByVal RecurringReferenceID As Long,  _
                    ByVal RecurringReferenceText As String,  _
                    ByVal Failure As Boolean,  _
                    ByVal TransNote As String,  _
                    ByVal Misc1 As String,  _
                    ByVal Misc2 As String,  _
                    ByVal Misc3 As String,  _
                    ByVal Misc4 As String) As System.Threading.Tasks.Task(Of Long) Implements IPSTools.ToolsSoap.UpdateCreditCardTransactionAsync
            Return MyBase.Channel.UpdateCreditCardTransactionAsync(Card_TransTable, Card_TransID, IVR_HistoryID, IVR_ProfileID, Web_HistoryID, TransDateTime, CustomerID, CustomerAccountID, FirstName, LastName, BillAddr1, BillAddr2, BillCity, BillState, BillZip, AccountLast4, AccountType, Fee, Amount, TransAmount, TransIsDebit, TransIsCredit, TransIsChargeback, TransIsVoid, WasVoided, VoidReferenceID, Reconciled, DataTokenID, MerchantID, MerchantReference, MerchantRequestID, MerchantDecision, MerchantReasonCode, MerchantAuthCode, MerchantAVSCode, MerchantBatchID, ReconBatchID, ReconDateTime, RecurringPayment, RecurringReferenceID, RecurringReferenceText, Failure, TransNote, Misc1, Misc2, Misc3, Misc4)
        End Function
        
        Public Function LogWebHistory( _
                    ByVal Web_HistoryTable As String,  _
                    ByVal Web_ProfileID As Long,  _
                    ByVal SessionID As String,  _
                    ByVal SessionIP As String,  _
                    ByVal SessionStart As Date,  _
                    ByVal SessionFinish As Date,  _
                    ByVal Schedule As String,  _
                    ByVal Credentials As String,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal CardTransID As Long,  _
                    ByVal ACHTransID As Long,  _
                    ByVal WebError As Boolean,  _
                    ByVal TextCaption1 As String,  _
                    ByVal TextCaption2 As String,  _
                    ByVal TextCaption3 As String,  _
                    ByVal TextCaption4 As String,  _
                    ByVal TextCaption5 As String,  _
                    ByVal TextCaption6 As String,  _
                    ByVal TextCaption7 As String,  _
                    ByVal TextCaption8 As String,  _
                    ByVal Text1 As String,  _
                    ByVal Text2 As String,  _
                    ByVal Text3 As String,  _
                    ByVal Text4 As String,  _
                    ByVal Text5 As String,  _
                    ByVal Text6 As String,  _
                    ByVal Text7 As String,  _
                    ByVal Text8 As String,  _
                    ByVal DateCaption1 As String,  _
                    ByVal DateCaption2 As String,  _
                    ByVal DateCaption3 As String,  _
                    ByVal DateCaption4 As String,  _
                    ByVal Date1 As Date,  _
                    ByVal Date2 As Date,  _
                    ByVal Date3 As Date,  _
                    ByVal Date4 As Date,  _
                    ByVal IntegerCaption1 As String,  _
                    ByVal IntegerCaption2 As String,  _
                    ByVal IntegerCaption3 As String,  _
                    ByVal IntegerCaption4 As String,  _
                    ByVal Integer1 As Long,  _
                    ByVal Integer2 As Long,  _
                    ByVal Integer3 As Long,  _
                    ByVal Integer4 As Long,  _
                    ByVal NumericCaption1 As String,  _
                    ByVal NumericCaption2 As String,  _
                    ByVal NumericCaption3 As String,  _
                    ByVal NumericCaption4 As String,  _
                    ByVal Numeric1 As Decimal,  _
                    ByVal Numeric2 As Decimal,  _
                    ByVal Numeric3 As Decimal,  _
                    ByVal Numeric4 As Decimal,  _
                    ByVal MoneyCaption1 As String,  _
                    ByVal MoneyCaption2 As String,  _
                    ByVal MoneyCaption3 As String,  _
                    ByVal MoneyCaption4 As String,  _
                    ByVal Money1 As Double,  _
                    ByVal Money2 As Double,  _
                    ByVal Money3 As Double,  _
                    ByVal Money4 As Double,  _
                    ByVal BitCaption1 As String,  _
                    ByVal BitCaption2 As String,  _
                    ByVal BitCaption3 As String,  _
                    ByVal BitCaption4 As String,  _
                    ByVal Bit1 As Boolean,  _
                    ByVal Bit2 As Boolean,  _
                    ByVal Bit3 As Boolean,  _
                    ByVal Bit4 As Boolean) As Long Implements IPSTools.ToolsSoap.LogWebHistory
            Return MyBase.Channel.LogWebHistory(Web_HistoryTable, Web_ProfileID, SessionID, SessionIP, SessionStart, SessionFinish, Schedule, Credentials, CustomerID, CustomerAccountID, CardTransID, ACHTransID, WebError, TextCaption1, TextCaption2, TextCaption3, TextCaption4, TextCaption5, TextCaption6, TextCaption7, TextCaption8, Text1, Text2, Text3, Text4, Text5, Text6, Text7, Text8, DateCaption1, DateCaption2, DateCaption3, DateCaption4, Date1, Date2, Date3, Date4, IntegerCaption1, IntegerCaption2, IntegerCaption3, IntegerCaption4, Integer1, Integer2, Integer3, Integer4, NumericCaption1, NumericCaption2, NumericCaption3, NumericCaption4, Numeric1, Numeric2, Numeric3, Numeric4, MoneyCaption1, MoneyCaption2, MoneyCaption3, MoneyCaption4, Money1, Money2, Money3, Money4, BitCaption1, BitCaption2, BitCaption3, BitCaption4, Bit1, Bit2, Bit3, Bit4)
        End Function
        
        Public Function LogWebHistoryAsync( _
                    ByVal Web_HistoryTable As String,  _
                    ByVal Web_ProfileID As Long,  _
                    ByVal SessionID As String,  _
                    ByVal SessionIP As String,  _
                    ByVal SessionStart As Date,  _
                    ByVal SessionFinish As Date,  _
                    ByVal Schedule As String,  _
                    ByVal Credentials As String,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal CardTransID As Long,  _
                    ByVal ACHTransID As Long,  _
                    ByVal WebError As Boolean,  _
                    ByVal TextCaption1 As String,  _
                    ByVal TextCaption2 As String,  _
                    ByVal TextCaption3 As String,  _
                    ByVal TextCaption4 As String,  _
                    ByVal TextCaption5 As String,  _
                    ByVal TextCaption6 As String,  _
                    ByVal TextCaption7 As String,  _
                    ByVal TextCaption8 As String,  _
                    ByVal Text1 As String,  _
                    ByVal Text2 As String,  _
                    ByVal Text3 As String,  _
                    ByVal Text4 As String,  _
                    ByVal Text5 As String,  _
                    ByVal Text6 As String,  _
                    ByVal Text7 As String,  _
                    ByVal Text8 As String,  _
                    ByVal DateCaption1 As String,  _
                    ByVal DateCaption2 As String,  _
                    ByVal DateCaption3 As String,  _
                    ByVal DateCaption4 As String,  _
                    ByVal Date1 As Date,  _
                    ByVal Date2 As Date,  _
                    ByVal Date3 As Date,  _
                    ByVal Date4 As Date,  _
                    ByVal IntegerCaption1 As String,  _
                    ByVal IntegerCaption2 As String,  _
                    ByVal IntegerCaption3 As String,  _
                    ByVal IntegerCaption4 As String,  _
                    ByVal Integer1 As Long,  _
                    ByVal Integer2 As Long,  _
                    ByVal Integer3 As Long,  _
                    ByVal Integer4 As Long,  _
                    ByVal NumericCaption1 As String,  _
                    ByVal NumericCaption2 As String,  _
                    ByVal NumericCaption3 As String,  _
                    ByVal NumericCaption4 As String,  _
                    ByVal Numeric1 As Decimal,  _
                    ByVal Numeric2 As Decimal,  _
                    ByVal Numeric3 As Decimal,  _
                    ByVal Numeric4 As Decimal,  _
                    ByVal MoneyCaption1 As String,  _
                    ByVal MoneyCaption2 As String,  _
                    ByVal MoneyCaption3 As String,  _
                    ByVal MoneyCaption4 As String,  _
                    ByVal Money1 As Double,  _
                    ByVal Money2 As Double,  _
                    ByVal Money3 As Double,  _
                    ByVal Money4 As Double,  _
                    ByVal BitCaption1 As String,  _
                    ByVal BitCaption2 As String,  _
                    ByVal BitCaption3 As String,  _
                    ByVal BitCaption4 As String,  _
                    ByVal Bit1 As Boolean,  _
                    ByVal Bit2 As Boolean,  _
                    ByVal Bit3 As Boolean,  _
                    ByVal Bit4 As Boolean) As System.Threading.Tasks.Task(Of Long) Implements IPSTools.ToolsSoap.LogWebHistoryAsync
            Return MyBase.Channel.LogWebHistoryAsync(Web_HistoryTable, Web_ProfileID, SessionID, SessionIP, SessionStart, SessionFinish, Schedule, Credentials, CustomerID, CustomerAccountID, CardTransID, ACHTransID, WebError, TextCaption1, TextCaption2, TextCaption3, TextCaption4, TextCaption5, TextCaption6, TextCaption7, TextCaption8, Text1, Text2, Text3, Text4, Text5, Text6, Text7, Text8, DateCaption1, DateCaption2, DateCaption3, DateCaption4, Date1, Date2, Date3, Date4, IntegerCaption1, IntegerCaption2, IntegerCaption3, IntegerCaption4, Integer1, Integer2, Integer3, Integer4, NumericCaption1, NumericCaption2, NumericCaption3, NumericCaption4, Numeric1, Numeric2, Numeric3, Numeric4, MoneyCaption1, MoneyCaption2, MoneyCaption3, MoneyCaption4, Money1, Money2, Money3, Money4, BitCaption1, BitCaption2, BitCaption3, BitCaption4, Bit1, Bit2, Bit3, Bit4)
        End Function
        
        Public Function UpdateWebHistoryEventLog(ByVal Web_HistoryTable As String, ByVal Web_HistoryID As Long, ByVal Web_EventLog As String, ByVal SessionFinish As Date, ByVal CustomerAccountID As String, ByVal CardTransID As Long, ByVal ACHTransID As Long, ByVal WebError As Boolean) As Object Implements IPSTools.ToolsSoap.UpdateWebHistoryEventLog
            Return MyBase.Channel.UpdateWebHistoryEventLog(Web_HistoryTable, Web_HistoryID, Web_EventLog, SessionFinish, CustomerAccountID, CardTransID, ACHTransID, WebError)
        End Function
        
        Public Function UpdateWebHistoryEventLogAsync(ByVal Web_HistoryTable As String, ByVal Web_HistoryID As Long, ByVal Web_EventLog As String, ByVal SessionFinish As Date, ByVal CustomerAccountID As String, ByVal CardTransID As Long, ByVal ACHTransID As Long, ByVal WebError As Boolean) As System.Threading.Tasks.Task(Of Object) Implements IPSTools.ToolsSoap.UpdateWebHistoryEventLogAsync
            Return MyBase.Channel.UpdateWebHistoryEventLogAsync(Web_HistoryTable, Web_HistoryID, Web_EventLog, SessionFinish, CustomerAccountID, CardTransID, ACHTransID, WebError)
        End Function
        
        Public Function UpdateWebHistoryCustom( _
                    ByVal Web_HistoryTable As String,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal SessionFinish As Date,  _
                    ByVal Schedule As String,  _
                    ByVal Credentials As String,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal CardTransID As Long,  _
                    ByVal ACHTransID As Long,  _
                    ByVal WebError As Boolean,  _
                    ByVal TextCaption1 As String,  _
                    ByVal TextCaption2 As String,  _
                    ByVal TextCaption3 As String,  _
                    ByVal TextCaption4 As String,  _
                    ByVal TextCaption5 As String,  _
                    ByVal TextCaption6 As String,  _
                    ByVal TextCaption7 As String,  _
                    ByVal TextCaption8 As String,  _
                    ByVal Text1 As String,  _
                    ByVal Text2 As String,  _
                    ByVal Text3 As String,  _
                    ByVal Text4 As String,  _
                    ByVal Text5 As String,  _
                    ByVal Text6 As String,  _
                    ByVal Text7 As String,  _
                    ByVal Text8 As String,  _
                    ByVal DateCaption1 As String,  _
                    ByVal DateCaption2 As String,  _
                    ByVal DateCaption3 As String,  _
                    ByVal DateCaption4 As String,  _
                    ByVal Date1 As Date,  _
                    ByVal Date2 As Date,  _
                    ByVal Date3 As Date,  _
                    ByVal Date4 As Date,  _
                    ByVal IntegerCaption1 As String,  _
                    ByVal IntegerCaption2 As String,  _
                    ByVal IntegerCaption3 As String,  _
                    ByVal IntegerCaption4 As String,  _
                    ByVal Integer1 As Long,  _
                    ByVal Integer2 As Long,  _
                    ByVal Integer3 As Long,  _
                    ByVal Integer4 As Long,  _
                    ByVal NumericCaption1 As String,  _
                    ByVal NumericCaption2 As String,  _
                    ByVal NumericCaption3 As String,  _
                    ByVal NumericCaption4 As String,  _
                    ByVal Numeric1 As Decimal,  _
                    ByVal Numeric2 As Decimal,  _
                    ByVal Numeric3 As Decimal,  _
                    ByVal Numeric4 As Decimal,  _
                    ByVal MoneyCaption1 As String,  _
                    ByVal MoneyCaption2 As String,  _
                    ByVal MoneyCaption3 As String,  _
                    ByVal MoneyCaption4 As String,  _
                    ByVal Money1 As Double,  _
                    ByVal Money2 As Double,  _
                    ByVal Money3 As Double,  _
                    ByVal Money4 As Double,  _
                    ByVal BitCaption1 As String,  _
                    ByVal BitCaption2 As String,  _
                    ByVal BitCaption3 As String,  _
                    ByVal BitCaption4 As String,  _
                    ByVal Bit1 As Boolean,  _
                    ByVal Bit2 As Boolean,  _
                    ByVal Bit3 As Boolean,  _
                    ByVal Bit4 As Boolean) As Long Implements IPSTools.ToolsSoap.UpdateWebHistoryCustom
            Return MyBase.Channel.UpdateWebHistoryCustom(Web_HistoryTable, Web_HistoryID, SessionFinish, Schedule, Credentials, CustomerID, CustomerAccountID, CardTransID, ACHTransID, WebError, TextCaption1, TextCaption2, TextCaption3, TextCaption4, TextCaption5, TextCaption6, TextCaption7, TextCaption8, Text1, Text2, Text3, Text4, Text5, Text6, Text7, Text8, DateCaption1, DateCaption2, DateCaption3, DateCaption4, Date1, Date2, Date3, Date4, IntegerCaption1, IntegerCaption2, IntegerCaption3, IntegerCaption4, Integer1, Integer2, Integer3, Integer4, NumericCaption1, NumericCaption2, NumericCaption3, NumericCaption4, Numeric1, Numeric2, Numeric3, Numeric4, MoneyCaption1, MoneyCaption2, MoneyCaption3, MoneyCaption4, Money1, Money2, Money3, Money4, BitCaption1, BitCaption2, BitCaption3, BitCaption4, Bit1, Bit2, Bit3, Bit4)
        End Function
        
        Public Function UpdateWebHistoryCustomAsync( _
                    ByVal Web_HistoryTable As String,  _
                    ByVal Web_HistoryID As Long,  _
                    ByVal SessionFinish As Date,  _
                    ByVal Schedule As String,  _
                    ByVal Credentials As String,  _
                    ByVal CustomerID As Long,  _
                    ByVal CustomerAccountID As String,  _
                    ByVal CardTransID As Long,  _
                    ByVal ACHTransID As Long,  _
                    ByVal WebError As Boolean,  _
                    ByVal TextCaption1 As String,  _
                    ByVal TextCaption2 As String,  _
                    ByVal TextCaption3 As String,  _
                    ByVal TextCaption4 As String,  _
                    ByVal TextCaption5 As String,  _
                    ByVal TextCaption6 As String,  _
                    ByVal TextCaption7 As String,  _
                    ByVal TextCaption8 As String,  _
                    ByVal Text1 As String,  _
                    ByVal Text2 As String,  _
                    ByVal Text3 As String,  _
                    ByVal Text4 As String,  _
                    ByVal Text5 As String,  _
                    ByVal Text6 As String,  _
                    ByVal Text7 As String,  _
                    ByVal Text8 As String,  _
                    ByVal DateCaption1 As String,  _
                    ByVal DateCaption2 As String,  _
                    ByVal DateCaption3 As String,  _
                    ByVal DateCaption4 As String,  _
                    ByVal Date1 As Date,  _
                    ByVal Date2 As Date,  _
                    ByVal Date3 As Date,  _
                    ByVal Date4 As Date,  _
                    ByVal IntegerCaption1 As String,  _
                    ByVal IntegerCaption2 As String,  _
                    ByVal IntegerCaption3 As String,  _
                    ByVal IntegerCaption4 As String,  _
                    ByVal Integer1 As Long,  _
                    ByVal Integer2 As Long,  _
                    ByVal Integer3 As Long,  _
                    ByVal Integer4 As Long,  _
                    ByVal NumericCaption1 As String,  _
                    ByVal NumericCaption2 As String,  _
                    ByVal NumericCaption3 As String,  _
                    ByVal NumericCaption4 As String,  _
                    ByVal Numeric1 As Decimal,  _
                    ByVal Numeric2 As Decimal,  _
                    ByVal Numeric3 As Decimal,  _
                    ByVal Numeric4 As Decimal,  _
                    ByVal MoneyCaption1 As String,  _
                    ByVal MoneyCaption2 As String,  _
                    ByVal MoneyCaption3 As String,  _
                    ByVal MoneyCaption4 As String,  _
                    ByVal Money1 As Double,  _
                    ByVal Money2 As Double,  _
                    ByVal Money3 As Double,  _
                    ByVal Money4 As Double,  _
                    ByVal BitCaption1 As String,  _
                    ByVal BitCaption2 As String,  _
                    ByVal BitCaption3 As String,  _
                    ByVal BitCaption4 As String,  _
                    ByVal Bit1 As Boolean,  _
                    ByVal Bit2 As Boolean,  _
                    ByVal Bit3 As Boolean,  _
                    ByVal Bit4 As Boolean) As System.Threading.Tasks.Task(Of Long) Implements IPSTools.ToolsSoap.UpdateWebHistoryCustomAsync
            Return MyBase.Channel.UpdateWebHistoryCustomAsync(Web_HistoryTable, Web_HistoryID, SessionFinish, Schedule, Credentials, CustomerID, CustomerAccountID, CardTransID, ACHTransID, WebError, TextCaption1, TextCaption2, TextCaption3, TextCaption4, TextCaption5, TextCaption6, TextCaption7, TextCaption8, Text1, Text2, Text3, Text4, Text5, Text6, Text7, Text8, DateCaption1, DateCaption2, DateCaption3, DateCaption4, Date1, Date2, Date3, Date4, IntegerCaption1, IntegerCaption2, IntegerCaption3, IntegerCaption4, Integer1, Integer2, Integer3, Integer4, NumericCaption1, NumericCaption2, NumericCaption3, NumericCaption4, Numeric1, Numeric2, Numeric3, Numeric4, MoneyCaption1, MoneyCaption2, MoneyCaption3, MoneyCaption4, Money1, Money2, Money3, Money4, BitCaption1, BitCaption2, BitCaption3, BitCaption4, Bit1, Bit2, Bit3, Bit4)
        End Function
    End Class
End Namespace
