'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace App_In_Maintenance
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.activetelesource.com/webservices/", ConfigurationName:="App_In_Maintenance.UtilitySoap")>  _
    Public Interface UtilitySoap
        
        'CODEGEN: Generating message contract since element name App_Name from namespace http://www.activetelesource.com/webservices/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.activetelesource.com/webservices/App_In_Maintenance", ReplyAction:="*")>  _
        Function App_In_Maintenance(ByVal request As App_In_Maintenance.App_In_MaintenanceRequest) As App_In_Maintenance.App_In_MaintenanceResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class App_In_MaintenanceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="App_In_Maintenance", [Namespace]:="http://www.activetelesource.com/webservices/", Order:=0)>  _
        Public Body As App_In_Maintenance.App_In_MaintenanceRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As App_In_Maintenance.App_In_MaintenanceRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.activetelesource.com/webservices/")>  _
    Partial Public Class App_In_MaintenanceRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public App_Name As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal App_Name As String)
            MyBase.New
            Me.App_Name = App_Name
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class App_In_MaintenanceResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="App_In_MaintenanceResponse", [Namespace]:="http://www.activetelesource.com/webservices/", Order:=0)>  _
        Public Body As App_In_Maintenance.App_In_MaintenanceResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As App_In_Maintenance.App_In_MaintenanceResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.activetelesource.com/webservices/")>  _
    Partial Public Class App_In_MaintenanceResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public App_In_MaintenanceResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal App_In_MaintenanceResult As Boolean)
            MyBase.New
            Me.App_In_MaintenanceResult = App_In_MaintenanceResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface UtilitySoapChannel
        Inherits App_In_Maintenance.UtilitySoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UtilitySoapClient
        Inherits System.ServiceModel.ClientBase(Of App_In_Maintenance.UtilitySoap)
        Implements App_In_Maintenance.UtilitySoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function App_In_Maintenance_UtilitySoap_App_In_Maintenance(ByVal request As App_In_Maintenance.App_In_MaintenanceRequest) As App_In_Maintenance.App_In_MaintenanceResponse Implements App_In_Maintenance.UtilitySoap.App_In_Maintenance
            Return MyBase.Channel.App_In_Maintenance(request)
        End Function
        
        Public Function App_In_Maintenance(ByVal App_Name As String) As Boolean
            Dim inValue As App_In_Maintenance.App_In_MaintenanceRequest = New App_In_Maintenance.App_In_MaintenanceRequest()
            inValue.Body = New App_In_Maintenance.App_In_MaintenanceRequestBody()
            inValue.Body.App_Name = App_Name
            Dim retVal As App_In_Maintenance.App_In_MaintenanceResponse = CType(Me,App_In_Maintenance.UtilitySoap).App_In_Maintenance(inValue)
            Return retVal.Body.App_In_MaintenanceResult
        End Function
    End Class
End Namespace
