#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel.DataAnnotations;
using AtiWrapperServicesORM.OpenAccess;

namespace AtiWrapperServicesORM.OpenAccess	
{
	public partial class ServiceMessageHeader
	{
		private int _id;
		[Required()]
		[Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _order;
		[Required()]
		public virtual int Order
		{
			get
			{
				return this._order;
			}
			set
			{
				this._order = value;
			}
		}
		
		private string _typeName;
		[Required()]
		public virtual string TypeName
		{
			get
			{
				return this._typeName;
			}
			set
			{
				this._typeName = value;
			}
		}
		
		private string _assemblyName;
		[Required()]
		public virtual string AssemblyName
		{
			get
			{
				return this._assemblyName;
			}
			set
			{
				this._assemblyName = value;
			}
		}
		
		private int? _serviceMethod_Id;
		[Required()]
		public virtual int? ServiceMethod_Id
		{
			get
			{
				return this._serviceMethod_Id;
			}
			set
			{
				this._serviceMethod_Id = value;
			}
		}
		
		private IList<ServiceType> _serviceTypes = new List<ServiceType>();
		public virtual IList<ServiceType> ServiceTypes
		{
			get
			{
				return this._serviceTypes;
			}
		}
		
	}
}
#pragma warning restore 1591
