#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel.DataAnnotations;
using AtiWrapperServicesORM.OpenAccess;

namespace AtiWrapperServicesORM.OpenAccess	
{
	public partial class ServiceMethod
	{
		private int _id;
		[Required()]
		[Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		[Required()]
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private int _endpointAddressModifierOption;
		[Required()]
		public virtual int EndpointAddressModifierOption
		{
			get
			{
				return this._endpointAddressModifierOption;
			}
			set
			{
				this._endpointAddressModifierOption = value;
			}
		}
		
		private int _serviceName_Id;
		[Required()]
		public virtual int ServiceName_Id
		{
			get
			{
				return this._serviceName_Id;
			}
			set
			{
				this._serviceName_Id = value;
			}
		}
		
		private string _xmlTemplate;
		public virtual string XmlTemplate
		{
			get
			{
				return this._xmlTemplate;
			}
			set
			{
				this._xmlTemplate = value;
			}
		}
		
		private string _xmlTypeSignature;
		public virtual string XmlTypeSignature
		{
			get
			{
				return this._xmlTypeSignature;
			}
			set
			{
				this._xmlTypeSignature = value;
			}
		}
		
		private ServiceName _serviceName;
		public virtual ServiceName ServiceName
		{
			get
			{
				return this._serviceName;
			}
			set
			{
				this._serviceName = value;
			}
		}
		
		private IList<WrapperMethod> _wrapperMethods = new List<WrapperMethod>();
		public virtual IList<WrapperMethod> WrapperMethods
		{
			get
			{
				return this._wrapperMethods;
			}
		}
		
		private IList<InputParamater> _inputParamaters = new List<InputParamater>();
		public virtual IList<InputParamater> InputParamaters
		{
			get
			{
				return this._inputParamaters;
			}
		}
		
	}
}
#pragma warning restore 1591
