#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel.DataAnnotations;
using AtiWrapperServicesORM.OpenAccess;

namespace AtiWrapperServicesORM.OpenAccess	
{
	public partial class ServiceType
	{
		private int _id;
		[Required()]
		[Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		[Required()]
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private bool _isSystemType;
		[Required()]
		public virtual bool IsSystemType
		{
			get
			{
				return this._isSystemType;
			}
			set
			{
				this._isSystemType = value;
			}
		}
		
		private string _typeName;
		[Required()]
		public virtual string TypeName
		{
			get
			{
				return this._typeName;
			}
			set
			{
				this._typeName = value;
			}
		}
		
		private int? _parentId;
		public virtual int? ParentId
		{
			get
			{
				return this._parentId;
			}
			set
			{
				this._parentId = value;
			}
		}
		
		private bool _isCollectionType;
		[Required()]
		public virtual bool IsCollectionType
		{
			get
			{
				return this._isCollectionType;
			}
			set
			{
				this._isCollectionType = value;
			}
		}
		
		private int? _inputParamater_Id;
		public virtual int? InputParamater_Id
		{
			get
			{
				return this._inputParamater_Id;
			}
			set
			{
				this._inputParamater_Id = value;
			}
		}
		
		private int? _returnType_Id;
		public virtual int? ReturnType_Id
		{
			get
			{
				return this._returnType_Id;
			}
			set
			{
				this._returnType_Id = value;
			}
		}
		
		private int? _serviceMessageHeader_Id;
		public virtual int? ServiceMessageHeader_Id
		{
			get
			{
				return this._serviceMessageHeader_Id;
			}
			set
			{
				this._serviceMessageHeader_Id = value;
			}
		}
		
		private bool _isEnum;
		[Required()]
		public virtual bool IsEnum
		{
			get
			{
				return this._isEnum;
			}
			set
			{
				this._isEnum = value;
			}
		}
		
		private int _logParameter;
		[Required()]
		public virtual int LogParameter
		{
			get
			{
				return this._logParameter;
			}
			set
			{
				this._logParameter = value;
			}
		}
		
		private int _qualifiedName_Id;
		[Required()]
		public virtual int QualifiedName_Id
		{
			get
			{
				return this._qualifiedName_Id;
			}
			set
			{
				this._qualifiedName_Id = value;
			}
		}
		
		private InputParamater _inputParamater;
		public virtual InputParamater InputParamater
		{
			get
			{
				return this._inputParamater;
			}
			set
			{
				this._inputParamater = value;
			}
		}
		
		private ReturnType _returnType;
		public virtual ReturnType ReturnType
		{
			get
			{
				return this._returnType;
			}
			set
			{
				this._returnType = value;
			}
		}
		
		private QualifiedName _qualifiedName;
		public virtual QualifiedName QualifiedName
		{
			get
			{
				return this._qualifiedName;
			}
			set
			{
				this._qualifiedName = value;
			}
		}
		
		private ServiceMessageHeader _serviceMessageHeader;
		public virtual ServiceMessageHeader ServiceMessageHeader
		{
			get
			{
				return this._serviceMessageHeader;
			}
			set
			{
				this._serviceMessageHeader = value;
			}
		}
		
	}
}
#pragma warning restore 1591
