#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel.DataAnnotations;
using AtiWrapperServices.AtiWrapperServicesEnums;
using AtiWrapperServicesORM.OpenAccess;

namespace AtiWrapperServicesORM.OpenAccess	
{
	public partial class ServiceURL
	{
		private int _id;
		[Required()]
		[Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _productionURL;
		public virtual string ProductionURL
		{
			get
			{
				return this._productionURL;
			}
			set
			{
				this._productionURL = value;
			}
		}
		
		private string _testURL;
		public virtual string TestURL
		{
			get
			{
				return this._testURL;
			}
			set
			{
				this._testURL = value;
			}
		}
		
		private int _customer_Id;
		[Required()]
		public virtual int Customer_Id
		{
			get
			{
				return this._customer_Id;
			}
			set
			{
				this._customer_Id = value;
			}
		}
		
		private UseSource _productionUseSource;
		public virtual UseSource ProductionUseSource
		{
			get
			{
				return this._productionUseSource;
			}
			set
			{
				this._productionUseSource = value;
			}
		}
		
		private string _productionWSDL;
		public virtual string ProductionWSDL
		{
			get
			{
				return this._productionWSDL;
			}
			set
			{
				this._productionWSDL = value;
			}
		}
		
		private string _productionCode;
		public virtual string ProductionCode
		{
			get
			{
				return this._productionCode;
			}
			set
			{
				this._productionCode = value;
			}
		}
		
		private UseSource _testUseSource;
		public virtual UseSource TestUseSource
		{
			get
			{
				return this._testUseSource;
			}
			set
			{
				this._testUseSource = value;
			}
		}
		
		private string _testWSDL;
		public virtual string TestWSDL
		{
			get
			{
				return this._testWSDL;
			}
			set
			{
				this._testWSDL = value;
			}
		}
		
		private string _testCode;
		public virtual string TestCode
		{
			get
			{
				return this._testCode;
			}
			set
			{
				this._testCode = value;
			}
		}
		
		private Customer _customer;
		public virtual Customer Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
		}
		
		private IList<ServiceName> _serviceNames = new List<ServiceName>();
		public virtual IList<ServiceName> ServiceNames
		{
			get
			{
				return this._serviceNames;
			}
		}
		
	}
}
#pragma warning restore 1591
