#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel.DataAnnotations;
using AtiWrapperServicesORM.OpenAccess;

namespace AtiWrapperServicesORM.OpenAccess	
{
	public partial class WrapperValue
	{
		private int _id;
		[Required()]
		[Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _value;
		[Required()]
		public virtual string Value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		
		private int? _defaultWrapperValueProperty_Id;
		public virtual int? DefaultWrapperValueProperty_Id
		{
			get
			{
				return this._defaultWrapperValueProperty_Id;
			}
			set
			{
				this._defaultWrapperValueProperty_Id = value;
			}
		}
		
		private int? _testWrapperValueProperty_Id;
		public virtual int? TestWrapperValueProperty_Id
		{
			get
			{
				return this._testWrapperValueProperty_Id;
			}
			set
			{
				this._testWrapperValueProperty_Id = value;
			}
		}
		
		private WrapperValueProperty _wrapperValueProperty;
		public virtual WrapperValueProperty WrapperValueProperty
		{
			get
			{
				return this._wrapperValueProperty;
			}
			set
			{
				this._wrapperValueProperty = value;
			}
		}
		
		private WrapperValueProperty _wrapperValueProperty1;
		public virtual WrapperValueProperty WrapperValueProperty1
		{
			get
			{
				return this._wrapperValueProperty1;
			}
			set
			{
				this._wrapperValueProperty1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
