#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel.DataAnnotations;
using AtiWrapperServicesORM.OpenAccess;

namespace AtiWrapperServicesORM.OpenAccess	
{
	public partial class WrapperValueProperty
	{
		private int _id;
		[Required()]
		[Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private bool _required;
		[Required()]
		public virtual bool Required
		{
			get
			{
				return this._required;
			}
			set
			{
				this._required = value;
			}
		}
		
		private int? _wrapperReturnType_Id;
		public virtual int? WrapperReturnType_Id
		{
			get
			{
				return this._wrapperReturnType_Id;
			}
			set
			{
				this._wrapperReturnType_Id = value;
			}
		}
		
		private int? _wrapperInputParameter_Id;
		public virtual int? WrapperInputParameter_Id
		{
			get
			{
				return this._wrapperInputParameter_Id;
			}
			set
			{
				this._wrapperInputParameter_Id = value;
			}
		}
		
		private int? _wrapperMessageHeader_Id;
		public virtual int? WrapperMessageHeader_Id
		{
			get
			{
				return this._wrapperMessageHeader_Id;
			}
			set
			{
				this._wrapperMessageHeader_Id = value;
			}
		}
		
		private int _qualifiedName_Id;
		[Required()]
		public virtual int QualifiedName_Id
		{
			get
			{
				return this._qualifiedName_Id;
			}
			set
			{
				this._qualifiedName_Id = value;
			}
		}
		
		private WrapperInputParameter _wrapperInputParameter;
		public virtual WrapperInputParameter WrapperInputParameter
		{
			get
			{
				return this._wrapperInputParameter;
			}
			set
			{
				this._wrapperInputParameter = value;
			}
		}
		
		private WrapperReturnType _wrapperReturnType;
		public virtual WrapperReturnType WrapperReturnType
		{
			get
			{
				return this._wrapperReturnType;
			}
			set
			{
				this._wrapperReturnType = value;
			}
		}
		
		private WrapperMessageHeader _wrapperMessageHeader;
		public virtual WrapperMessageHeader WrapperMessageHeader
		{
			get
			{
				return this._wrapperMessageHeader;
			}
			set
			{
				this._wrapperMessageHeader = value;
			}
		}
		
		private QualifiedName _qualifiedName;
		public virtual QualifiedName QualifiedName
		{
			get
			{
				return this._qualifiedName;
			}
			set
			{
				this._qualifiedName = value;
			}
		}
		
		private IList<WrapperValue> _wrapperValues = new List<WrapperValue>();
		public virtual IList<WrapperValue> WrapperValues
		{
			get
			{
				return this._wrapperValues;
			}
		}
		
		private IList<WrapperValue> _wrapperValues1 = new List<WrapperValue>();
		public virtual IList<WrapperValue> WrapperValues1
		{
			get
			{
				return this._wrapperValues1;
			}
		}
		
	}
}
#pragma warning restore 1591
