#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel.DataAnnotations;
using AtiWrapperServicesORM.OpenAccess;

namespace AtiWrapperServicesORM.OpenAccess	
{
	public partial class WrapperMethod
	{
		private int _id;
		[Required()]
		[Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		[Required()]
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private int _serviceMethod_Id;
		[Required()]
		public virtual int ServiceMethod_Id
		{
			get
			{
				return this._serviceMethod_Id;
			}
			set
			{
				this._serviceMethod_Id = value;
			}
		}
		
		private ServiceMethod _serviceMethod;
		public virtual ServiceMethod ServiceMethod
		{
			get
			{
				return this._serviceMethod;
			}
			set
			{
				this._serviceMethod = value;
			}
		}
		
		private IList<WrapperInputParameter> _wrapperInputParameters = new List<WrapperInputParameter>();
		public virtual IList<WrapperInputParameter> WrapperInputParameters
		{
			get
			{
				return this._wrapperInputParameters;
			}
		}
		
		private IList<WrapperMessageHeader> _wrapperMessageHeaders = new List<WrapperMessageHeader>();
		public virtual IList<WrapperMessageHeader> WrapperMessageHeaders
		{
			get
			{
				return this._wrapperMessageHeaders;
			}
		}
		
		private IList<WrapperReturnType> _wrapperReturnTypes = new List<WrapperReturnType>();
		public virtual IList<WrapperReturnType> WrapperReturnTypes
		{
			get
			{
				return this._wrapperReturnTypes;
			}
		}
		
	}
}
#pragma warning restore 1591
