#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel.DataAnnotations;
using AtiWrapperServicesORM.OpenAccess;

namespace AtiWrapperServicesORM.OpenAccess	
{
	public partial class WrapperReturnType
	{
		private int _id;
		[Required()]
		[Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _wrapperMethod_Id;
		[Required()]
		public virtual int? WrapperMethod_Id
		{
			get
			{
				return this._wrapperMethod_Id;
			}
			set
			{
				this._wrapperMethod_Id = value;
			}
		}
		
		private int _returnEncoding;
		[Required()]
		public virtual int ReturnEncoding
		{
			get
			{
				return this._returnEncoding;
			}
			set
			{
				this._returnEncoding = value;
			}
		}
		
		private WrapperMethod _wrapperMethod;
		public virtual WrapperMethod WrapperMethod
		{
			get
			{
				return this._wrapperMethod;
			}
			set
			{
				this._wrapperMethod = value;
			}
		}
		
		private IList<WrapperValueProperty> _wrapperValueProperties = new List<WrapperValueProperty>();
		public virtual IList<WrapperValueProperty> WrapperValueProperties
		{
			get
			{
				return this._wrapperValueProperties;
			}
		}
		
	}
}
#pragma warning restore 1591
